# Generated by Django 4.2.27 on 2025-12-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questprogress',
            name='choices_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questprogress',
            name='choices_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
